spring.application.name=tickets

spring.datasource.url=jdbc:postgresql://localhost:5432/tickets
spring.datasource.username=${DB_USERNAME:hyfuser}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver



resend.api.key=${RESEND_API}
resend.from=onboarding@resend.dev