spring.application.name=tickets

spring.datasource.url=jdbc:postgresql://localhost:5432/tickets
spring.datasource.username=${DB_USERNAME:hyfuser}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver



spring.mail.host=smtp.resend.com
spring.mail.port=465
spring.mail.username=resend
spring.mail.password=${RESEND_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true