
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


resend.api.key=${RESEND_API}


logging.level.root=INFO
logging.level.org.springframework.jdbc.core=DEBUG